--changeset INSERT_INTO_TABLE_CARD
INSERT INTO duel_masters.card(CARD_NAME, CARD_TYPE, CIVILIZATION, RACE, MANA_COST, MANA_NUMBER, POWER, SPECIAL_ABILITY,ABILITY_TEXT )
VALUES
('Hanusa, Radiance Elemental','CREATURE','LIGHT','ANGEL_COMMAND',7,1,9500,'DOUBLE_BREAKER',null),
('Urth, Purifying Elemental','CREATURE','LIGHT','ANGEL_COMMAND',8,1,6000,'DOUBLE_BREAKER','At the end of each of your turns, you may untap this creature'),
('Aqua Sniper','CREATURE','WATER','LIQUID_PEOPLE',8,1,5000,null,' When you put this creature into the battle zone,choose up to 2 creatures in the battle zone and return them to their owners hands'),
('king Depthcon','CREATURE','WATER','LEVIATHAN',7,1,6000,'DOUBLE_BREAKER','This creature cant be blocked'),
('Deathliger, Lion of Chaos','CREATURE','DARK','DEMON_COMMAND',7,1,9000,'DOUBLE_BREAKER',null),
('Zagaan, Knight of Darkness','CREATURE','DARK','DEMON_COMMAND',6,1,7000,'DOUBLE_BREAKER',null),
('Scarlet Skyterror','CREATURE','FIRE','ARMORED_WYVERN',8,1,3000,null,'When you put this creature into the battle zone, destroys all creature that have "blocker"'),
('Astrocomet Dragon','CREATURE','FIRE','ARMORED_DRAGON',7,1,6000,'DOUBLE_BREAKER','Power attacker +4000 (While attacking, this creature gets +4000 power.'),
('Roaring Great-Horn','CREATURE','NATURE','HORNED_BEAST',7,1,8000,'DOUBLE_BREAKER','Power attacker +2000 (While attacking, this creature gets +2000 power.'),
('Deathblade Beetle','CREATURE','NATURE','GIANT_INSECT',5,1,3000,'DOUBLE_BREAKER','Power attacker +4000 (While attacking, this creature gets +4000 power.'),
('Chilias, the Oracle','CREATURE','LIGHT','LIGHT_BRINGER',4,1,2500,null,'When this creature would be destroyed, put into your hand instead'),
('Dia Nork, Moonlight Guardian','CREATURE','LIGHT','GUARDIAN',4,1,5000,'BLOCKER','This creature cant attack players.'),
('Emerald Grass','CREATURE','LIGHT','STARLIGHT_TREE',2,1,3000,'BLOCKER','This creature cant attack players.'),
('Frei, Vizier of Air','CREATURE','LIGHT','INITIATE',4,1,3000,null,'At the end of each of your turns, you may untap this creature.'),
('Gran Gure, Space Guardian','CREATURE','LIGHT','GUARDIAN',6,1,9000,'BLOCKER','This creature cant attack players'),
('Holy Awe','SPELL','LIGHT',null,6,1,9000,'SHIELD_TRIGGER','Tap all your opponnents creatures in the battle zone'),
('Iere, Vizier of Bullets','CREATURE','LIGHT','INITIATE',3,1,3000,null,null),
('Iocant, the Oracle','CREATURE','LIGHT','LIGHT_BRINGER',2,1,2000,'BLOCKER','1. While you have at least 1 Angel Command in the battle zone, this creature gets +2000 power. 2. This creature cant attack players'),
('La Ura Giga, Sky Guardian','CREATURE','LIGHT','GUARDIAN',1,1,2000,'BLOCKER','This creature cant attack players.'),
('Lah, Purification Enforcer','CREATURE','LIGHT','BERSERKER',5,1,5500,null,null),
('Laser Wing','SPELL','LIGHT',null,5,1,0,null,'Choose up to 2 of your creatures in the battlezone. They cant be blocked this turn'),
('Lok, Vizier of Hunting','CREATURE','LIGHT','INITIATE',4,1,4000,null,null),
('Miele, Vizier of Lightning','CREATURE','LIGHT','INITIATE',3,1,1000,null,'When you put this creature into the battlezone you may choose one of your opponnents creatures in the battlezone and tap it'),
('Moonlight Flash','SPELL','LIGHT',null,4,1,0,null,'Choose up to 2 of your opponnents creature in the battlezone and tap them'),
('Rayla, Truth Enforcer','CREATURE','LIGHT','BERSERKER',6,1,3000,null,'When you put this creature into the battlezone, search your deck. You may take a spell from your deck, show it to your opponnent and put it into your hand, then shuffle your deck.'),
('Reusel, the Oracle','CREATURE','LIGHT','LIGHT_BRINGER',2,1,2000,null,null),
('Ruby Grass','CREATURE','LIGHT','STARLIGHT_TREE',3,1,3000,'BLOCKER','1. This creature cant attack players. 2. At the end of each of your turns you may untap this creature'),
('Senatine, Jade Tree','CREATURE','LIGHT','STARLIGHT_TREE',3,1,4000,'BLOCKER','1. This creature cant attack players.'),
('Solar Ray','SPELL','LIGHT',null,2,1,0,'SHIELD_TRIGGER','Choose 1 of your opponents creatures in the battlezone and tap it'),
('Sonic Wing','SPELL','LIGHT',null,3,1,0,null,'Choose 1 of your creatures in the battlezone. It cant be blocked this turn'),
('Szubs Kin, Twilight Guardian','CREATURE','LIGHT','GUARDIAN',5,1,6000,'BLOCKER','This creature cant attack players'),
('Toel, Vizier of Hope','CREATURE','LIGHT','INITIATE',5,1,2000,null,'At the end of each of your turns, you may untap all your creatures in the battlezone'),
('Aqua Hulcus','CREATURE','WATER','LIQUID_PEOPLE',3,1,2000,null,'When you put this creature into the batlezone, you may draw a card'),
('Aqua Knight','CREATURE','WATER','LIQUID_PEOPLE',5,1,4000,null,'When this creature would be destroyed, return it to your hand instead'),
('Aqua Solider','CREATURE','WATER','LIQUID_PEOPLE',3,1,1000,null,'When this creature would be destroyed, return it to your hand instead'),
('Aqua Vehicle','CREATURE','WATER','LIQUID_PEOPLE',2,1,1000,null,null),
('Brain Serum','SPELL','WATER',null,4,1,0,'SHIELD_TRIGGER','Draw up to 2 cards'),
('Candy Drop','CREATURE','WATER','CYBER_VIRUS',3,1,1000,null,'This creature cant be blocked'),
('Candy Crystal Memory','SPELL','WATER',null,4,1,0,'SHIELD_TRIGGER','Search your deck, you may take a card from your deck and put it in your hand, then shuffle your deck'),
('Faerie Child','CREATURE','WATER','CYBER_VIRUS',4,1,2000,null,'This creature cant be blocked'),
('Hunter Fish','CREATURE','WATER','FISH',2,1,3000,'BLOCKER','This creature cant attack')

